app:
  host: 0.0.0.0
  port: 8081
database:
  host: postgres
  port: 5432
  name: "rotation"
  url: postgres://{user}:{password}@{host}:{port}/{dbname}?sslmode=disable
message_broker:
  host: amqp
  port: 5672
  url: amqp://{user}:{password}@{host}/

